time

[albums]
title = "미러볼뮤직 ─ ALBUMS"
url = "http://mirrorballmusic.co.kr/albums/"
entrySelector = "div.album-list div.album-item"
titleSelector = "h1.album-title"
linkSelector = "a.inner"
imageSelector = "div.tb img"
contentSelector = "h2.artist-name"
waitForSelector = "div.album-item"
